on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'ci/ami/AMIBuildConfig.js'

jobs:
  presubmit:
    environment: AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

    - name: Set up Go 
      uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
      with:
        go-version: 1.17

    - name: Test Presubmit Job
      run: |
        cd ci/ami
        git clone https://github.com/kubernetes-sigs/image-builder.git
        sed -i 's/capa-ami-/test-capa-ami-/' ./image-builder/images/capi/packer/ami/packer.json
        cd image-builder/images/capi
        make deps-ami
        cd ../../..
        curl -L https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v1.4.1/clusterawsadm-linux-amd64 -o clusterawsadm
        chmod +x clusterawsadm
        go run main.go -mode presubmit
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AMI_BUILD_CONFIG_FILENAME: "AMIBuildConfig.json"
          AMI_BUILD_CONFIG_DEFAULTS: "AMIBuildConfigDefaults.json"
          AMI_BUILD_SUPPORTED_OS: "amazon-2"
          AMI_BUILD_REGIONS: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_AMI_OWNER_ID: "570412231501"
