on:
  pull_request:
    branches:
      - main

jobs:
  presubmit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

    - name: Set up Go 
      uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
      with:
        go-version: 1.17

    - name: Test Presubmit Job
      run: |
        git clone https://github.com/kubernetes-sigs/image-builder.git
        sed 's/capa-ami-/test-capa-ami-/' ./image-builder/images/capi/packer/ami/packer.json
        cd image-builder/images/capi
        make deps-ami
        make build-ami-ubuntu-2004
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AMI_BUILD_CONFIG_FILENAME: "AMIBuildConfig.json"
          AWS_ID: ${{ secrets.AWS_ID }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
